### ISSUE TITLE
How to visualise the point cloud distance

### ISSUE THREAD

**Issue by weijiawang96** [unknownue/pdflow#6] opened 2023-03-06 13:20 UTC
Dear authors,

Which library did you use to draw this figure, i.e., lighter blue means cleaner & darker blue means noisier:
![image](https://user-images.githubusercontent.com/30146940/223121472-00799f69-0365-4846-888b-46086e6c7c67.png)

Thank you so much for your help

**Comment by unknownue** [comment] 2023-04-07 12:29
duplicate of #1

**Closed as completed by unknownue** 2023-04-07 12:29 UTC
